version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports: 
      - 2181:2181


  kafka: 
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  charts1:
    container_name: charts1
    build: ./microservice01
    ports: 
      - 9103:9103
    volumes:
      - ./microservice01:/app
    environment:
      - PORT=9103
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - kafka

  micro2:
    container_name: micro2
    build: ./microservice02
    ports: 
      - 9104:9104
    volumes:
      - ./microservice02:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_TOPIC: chart_1
      KAFKA_PRODUCER_TOPIC: chart_to_database
    depends_on:
      - kafka

  charts_to_database: 
    container_name: charts_to_database
    build: ./microservice04
    ports:
      - 9106:9106
    volumes:
      - ./microservice04:/app
    links:
      - mongodb_charts

  charts_from_database: 
    container_name: charts_from_database
    build: ./microservice05
    ports:
      - 9107:9107
    volumes:
      - ./microservice05:/app
    links:
      - mongodb_charts

  mongodb_charts:
    container_name: mongodb_charts
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  chart2_parser:
    container_name: chart2_parser
    build: ./chart2_parser
    ports: 
      - 9111:9111
    volumes:
      - ./chart2_parser:/app
    environment:
      - PORT=9111
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=chart2
    depends_on:
      - kafka

  chart2_creator:
    container_name: chart2_creator
    build: ./chart2_creator
    ports: 
      - 9112:9112
    volumes:
      - ./chart2_creator:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_TOPIC: chart_2
      KAFKA_PRODUCER_TOPIC: chart_to_database
    depends_on:
      - kafka

  chart3_parser:
    container_name: chart3_parser
    build: ./chart3_parser
    ports: 
      - 9113:9113
    volumes:
      - ./chart3_parser:/app
    environment:
      - PORT=9113
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=chart3
    depends_on:
      - kafka

  chart3_creator:
    container_name: chart3_creator
    build: ./chart3_creator
    ports: 
      - 9114:9114
    volumes:
      - ./chart3_creator:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_TOPIC: chart_3
      KAFKA_PRODUCER_TOPIC: chart_to_database
    depends_on:
      - kafka

  chart4_parser:
    container_name: chart4_parser
    build: ./chart4_parser
    ports: 
      - 9115:9115
    volumes:
      - ./chart4_parser:/app
    environment:
      - PORT=9115
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=chart4
    depends_on:
      - kafka

  chart4_creator:
    container_name: chart4_creator
    build: ./chart4_creator
    ports: 
      - 9116:9116
    volumes:
      - ./chart4_creator:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_TOPIC: chart_4
      KAFKA_PRODUCER_TOPIC: chart_to_database
    depends_on:
      - kafka

  chart5_parser:
    container_name: chart5_parser
    build: ./chart5_parser
    ports: 
      - 9117:9117
    volumes:
      - ./chart5_parser:/app
    environment:
      - PORT=9117
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=chart5
    depends_on:
      - kafka

  chart5_creator:
    container_name: chart5_creator
    build: ./chart5_creator
    ports: 
      - 9118:9118
    volumes:
      - ./chart5_creator:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_TOPIC: chart_5
      KAFKA_PRODUCER_TOPIC: chart_to_database
    depends_on:
      - kafka

volumes:
  data:
